### ISSUE TITLE
PHP 8.0 genKey not working

### ISSUE THREAD

**Issue by LelieL91** [opensource-socialnetwork/OssnServices#10]
I installed the latest version of ossnservice using PHP8.0, but I got this error when I try to generate the key.
md5 function seems requiring an argument
![immagine](https://user-images.githubusercontent.com/48968075/138331716-ad8b9259-ac67-455f-a53c-7967be0d7c9f.png)
This issue is not present using PHP 7.4

**Comment by lianglee** [comment]
Fixed thanks

**Comment by LelieL91** [comment]
> 
> 
> Fixed thanks

Sure, no problem, happy to help. Thanks for your time.
