### ISSUE TITLE
Group  join not working

### ISSUE THREAD

**Issue by developer-bhumika** [opensource-socialnetwork/OssnServices#16]
![image](https://github.com/opensource-socialnetwork/OssnServices/assets/86490602/169779b4-6a17-4ea4-bfb6-618ceb2728c4)

Please check and update me. I am getting response code 200 but api throwing an error.

**Comment by lianglee** [comment]
See my reply check your log

**Comment by lianglee** [comment]
Fixed in https://github.com/opensource-socialnetwork/OssnServices/commit/aad0ced4e29084224748f5196268ad0b32a18c7b

**Comment by developer-bhumika** [comment]
@lianglee I can not see any fixes. Its still same 
![image](https://github.com/opensource-socialnetwork/OssnServices/assets/86490602/b97b5088-cded-4ae3-a285-b929d0fb7c4d)

**Comment by lianglee** [comment]
Download latest source.  :)

**Comment by developer-bhumika** [comment]
I am using apis only for mobile app, i don't know how to install and where to install. can you please install new version for https://nihss.joincommunity.net/ ?

**Comment by lianglee** [comment]
Check again updated on that website.

**Comment by developer-bhumika** [comment]
@lianglee group join is still not working 

![image](https://github.com/opensource-socialnetwork/OssnServices/assets/86490602/c6430d4b-b760-44f9-8c1c-e864cedd0a12)

**Comment by lianglee** [comment]
Because request already there. Try again

**Comment by developer-bhumika** [comment]
@lianglee working now 👍
