### ISSUE TITLE
Private messages for a user end up in the inbox of another user.

### ISSUE THREAD

**Issue by DaveWoertman** [opensource-socialnetwork/OssnServices#2]
We have installed OSSN premium 5.6 for our website and we also have the OSSNServices and the mobile app running for our domain.
We make use of the OSSNMessages component to send private messages to other users.
Now 1 user (lets call him user X)has shared a video of him using the mobile app. He is looking at the messages he got from user Y. There is 1 message that is meant for user X, so that is correct. BUT he also sees other messages that user Y has sent to users Z, A, B, C and so fort.
So it looks as if the mobile app doesn't filter out the correct messages per user. 
Is this a known issue?

I haven't been able to reproduce the issue on the website itself yet, but I am not 100% sure that it doesn't happen on the website too.

**Comment by lianglee** [comment]
Issue confirmed patch is on the way!

**Comment by lianglee** [comment]
@DaveWoertman please update it to Ossn Services 6.6 or apply the patch above!

https://www.opensource-socialnetwork.org/component/view/3174/ossnservices

**Comment by DaveWoertman** [comment]
Will do and will test the patch. Will come back to you with the results.
Thanks for the fast response
